### ISSUE TITLE
Error: Unknown pair style

### ISSUE THREAD

**Issue by rileyhanus** [ksaaskil/shc-python-tools#1]
Hi, I'm trying to work through your a-Si example for computing the spectral heat current. I'm pretty new to lammps but I have successfully run a number of lammps benchmarks using the python wrapper, including one that uses the pair_style command. However, when I try an run the silicon_example.py script I get 

ERROR: Unknown pair style sw (../force.cpp:246)
Last command: pair_style sw

which occurs when 'quench_Si.lmp' is being executed with iterateFile(lmp,"quench_Si.lmp").

Any ideas on how to fix this issue? I'm really excite at the possibility of using your spectral heat current post processing software in my research.

Best,
Riley

**Comment by ksaaskil** [comment]
Hi Riley! Sorry that this response comes so late, I have not been receiving notifications for this project for some reason. Pair style `sw` is part of the `MANYBODY` package so you need to install that. See the instructions [here](https://lammps.sandia.gov/doc/Build_package.html).
