### ISSUE TITLE
Computing force constants fails

### ISSUE THREAD

**Issue by ksaaskil** [ksaaskil/shc-python-tools#4]
With error `WARNING: Library error in lammps_scatter_atoms (../library.cpp:1227)`, most likely because the interface has changed.

**Comment by Tingliangstu** [comment]
When I used this program, I also encountered this problem ( WARNING: Library error in lammps_scatter_atoms (../library.cpp:1275)）, which resulted in the calculated spectral current in the SHC.txt being zero. The version of lammps I used was 5Jun2019. I am trying to solve this problem, hoping to make the program do its job. Have you fixed this bug? Thank you very much for sharing this code. I tried many ways to fix this bug but it didn't work. I would appreciate it if you could let me know if you have solved the problem.

**Comment by Tingliangstu** [comment]
Thank you very much for sharing this code.I tried many ways to fix this bug but it didn't work.I would appreciate it if you could let me know if you have solved the problem.

**Comment by ksaaskil** [comment]
The example is now finally fixed, by setting `atom_modify map yes` already in the LAMMPS input data file. This information is apparently now stored in the restart file and couldn't be overridden in `fcCalc.py`.
