### ISSUE TITLE
TypeError: 'numpy.float64' object cannot be interpreted as an index

### ISSUE THREAD

**Issue by Tingliangstu** [ksaaskil/shc-python-tools#5]
When I run the command **python silicon_example.py**, I get (**TypeError: 'numpy.float64' object cannot be interpreted as an index**). This should be the reason for the numpy version. The numpy version I used was 1.16.6. To solve this, I can replace the numpy version with 1.11.0. Another better option is to change line 155 in the SHCPostProc.py file to: daniellWindow = np.ones (**int** (Nwindow)) / Nwindow.

**Comment by ksaaskil** [comment]
Thanks for the comment and sorry I missed it, this has now been fixed.
