### ISSUE TITLE
Postprocess and structure

### ISSUE THREAD

**Issue by bbuenim** [ksaaskil/shc-python-tools#8]
Dear. Kimmo

After diligently reading your papers, I have tried to run your code.

fortunately, in the example, I run silicon_example.py and then get quench.log and simu.log.

However, After lammps work,  post processing might not worked I think. 

I got the lammps results but, but there is no outputs like 'frequencies_and_currents'

Do I need to run the other command to postprocessing except running ilicon_example.py ?

And when the Si.data was gnerated, the unexpected line at the last was also generated like 

Si.dat

.
.
.

Atoms

1 1 17.42690 8.89127 18.37165
2 1 7.03362 18.41037 17.09778

.
.
.

3942 1 95.74134 18.19972 19.59461

3943 1 29.19755 2.47895 0.48650

.77563                                                   <<<<<<< from  this line

3941 1 15.12689 0.73260 19.88166

3942 1 60.59043 5.60391 12.09781

3943 1 193.89100 7.43478 0.45105

908 10.99834 12.11397

 1 192.99451 7.16329 6.94463        <<<<<<< to the last line

this line changes randomly whenever I run repeatedly code.
For this reason, I could not go next step. just stop here

Could you also experience this problems ?

If not, could I directly read my material data to quench without make_atombox or my structure without quench.lmp ?
by trim the additional lines of Si.dat and changing name to Si2.dat, I read_data Si2.da. but It does not generate result of postprocess, just give lammps outs quench and simulation   

Thanks you
Best regards

**Comment by ksaaskil** [comment]
Hi Sue,

there are many questions here, let my try my best to address one by one. 

First, the script `silicon_example.py` is not supposed to create file 'frequencies_and_currents'. If you have pulled the latest version of the code, it outputs, for example, a file named `SHC.csv` containing the frequencies and heat currents. The code contains the following snippet writing this file:

```python
# silicon_example.py
   ...
    # Saving the frequencies and heat currents to CSV file
    np.savetxt(
        folder.joinpath("SHC.csv"),
        np.column_stack((postprocessor.oms_fft, postprocessor.SHC_smooth)),
        delimiter=",",
    )
```

Second, I haven't had any problems like you mentioned with `Si.dat`. When I run the script `silicon_example.py`, the output in `lammps-output/Si.dat` looks as follows:

```
# File written on 2021-12-25
3943 atoms
1 atom types

-0.10 200.00 xlo xhi
-0.10 20.00 ylo yhi
-0.10 20.00 zlo zhi

Masses

1 28.000

Atoms

1 1 155.66402 6.20140 18.91355
2 1 158.53260 13.95602 10.61655
...
3941 1 47.07889 19.07368 19.39608
3942 1 134.69254 13.21044 12.80335
3943 1 37.92241 17.74140 7.35842
```

You can generate the atomic coordinates in anyway you want. The only things needed specific for spectral heat current calculation are (1) atomic velocities and (2) atomic force constants. The Python module `sdhc` contains the code for performing this calculation.

**Comment by bbuenim** [comment]
Hi. Kimmo

Thanks for your kindness

I have gotten continuously the unexpected lines in the last of Si.dat duting repeat calculation.

It maybe comes from my python or linux systems because you can run correctly and I used same version.

**[Q1]** my python version 3.7.3 and is it because of my low version of python system? 



So, I run quenching by reading the manually trimmed Si2.dat (Si.dat erasing  the unexpected lines  )

As your comments, I got SHC.csv

but the results looks being wrong.

As your work, SHC.csv should contain the first column is oms(frequency) and the second is SHC

but In my result, the first column has non zero values and the second has only zeros like below:

0.000000000000000000e+00,0.000000000000000000e+00
1.005309649148733711e+10,0.000000000000000000e+00
2.010619298297467422e+10,0.000000000000000000e+00
                                          .
                                          .
                                          .
2.513073060942004688e+14,0.000000000000000000e+00
2.513173591906919688e+14,0.000000000000000000e+00
2.513274122871834375e+14,0.000000000000000000e+00


error message like below:

sdhc [INFO]: Changing chunk size to 15411!
Traceback (most recent call last):
  File "silicon_example.py", line 162, in <module>
    main()
  File "silicon_example.py", line 144, in main
    postprocessor = compute_sdhc(folder, restart_file)
  File "silicon_example.py", line 121, in compute_sdhc
    postprocessor.postProcess()
  File "/home/hellohuny/shc-python-tools-master/sdhc/SHCPostProc.py", line 294, in postProcess
    velArray = np.reshape(velArray, (NDOF, self.chunkSize), order="F")
  File "/home/hellohuny/anaconda3/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 292, in reshape
    return _wrapfunc(a, 'reshape', newshape, order=order)
  File "/home/hellohuny/anaconda3/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 56, in _wrapfunc
    return getattr(obj, method)(*args, **kwds)
ValueError: cannot reshape array of size 5270633 into shape (342,15411)

I confirmed the SHCPostProc.py but, i could not find the reason.

**[Q2]** Is It also maybe from numpy in my low version of python system? 

[Q3] Could I use the other potentials ,not sw of manybody , and binary material for this calculation? 

Thank so much
and
Happy New year!

Best regards,
