### ISSUE TITLE
How to reproduce figures in your paper and compute the MFP

### ISSUE THREAD

**Issue by visionshao** [ksaaskil/shc-python-tools#9]
Hi,  I have run the codes in the example folder. However, I found the results could not match the figures in this paper. Also, I am confused about how to compute the MFP according to the post-process results. Looking forward to your response ! Thank you in advance!

**Comment by ksaaskil** [comment]
Hi, 

> I found the results could not match the figures in this paper.

This repository and example code therein is just a small example to help you apply the method for your own systems. This repository does not show how to reproduce the results in the research papers.

As for the computation of MFP, please refer to the articles

- https://journals.aps.org/prb/abstract/10.1103/PhysRevB.91.115426
- https://journals.aps.org/prb/abstract/10.1103/PhysRevB.92.245411

I hope that helps, sorry for the delay in response.
